name: RSS Checker

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run RSS Checker
      run: |
        python rss_checker.py

    - name: Copy content to README.md
      run: |
        cp trending_news.md README.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add trending_news.md README.md processed_hashes.txt
        git commit -m "Update trending news and README"
        git push https://${{ secrets.PAT_TOKEN }}@github.com/drwiiche/google-trend-morocco.git HEAD:main
